### ISSUE TITLE
Model Rewrite v1

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#1256]
# Model Rewrite v1

This is a tracking issue for the total model rewrite.

```[tasklist]
## Todo:
- [ ] #1241
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1255
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1240
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1257
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1258
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1264
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1265
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1266
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1275
```
