### ISSUE TITLE
Add comprehensive unit and integration tests for API

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#1267]
# Add comprehensive unit and integration tests for API

API needs to be pretty heavily tested which should be easy to setup but tedious to do.

```[tasklist]
## Todo
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1268
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1269
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1270
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1271
- [ ] https://github.com/OpenCircuits/OpenCircuits/issues/1273
```
