### ISSUE TITLE
Add tests for API.Circuit

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#1268]
# Add tests for API.Circuit

```[tasklist]
## Todo
- [ ] `beginTransaction`, `commitTransaction`, `cancelTransaction`
- [ ] Metadata RW: `id`, `name`, `desc`, `thumbnail`
- [ ] Misc data RW: `locked`, `simEnabled`, `debugOptions`
- [ ] `pickObjAt`, `pickComponentAt`, `pickWireAt`, `pickPortAt`
- [ ] `pickObjRange`
- [ ] `getComponent`, `getWire`, `getPort`, `getObj`, `getObjs`, `getComponents`
- [ ] `getComponentInfo`
- [ ] `selectionsMidpoint`
- [ ] `placeComponentAt`
- [ ] `connectWire`
- [ ] `deleteObjs`
- [ ] `clearSelections`
- [ ] `undo`
- [ ] `redo`
- [ ] `copy`
- [ ] `reset`
- [ ] `serialize`
- [ ] `deserialize`
- [ ] `resize`
- [ ] `subscribe`
```
